"""Initial migration

Revision ID: 48e7896f9166
Revises: 
Create Date: 2023-12-02 23:08:16.929826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48e7896f9166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sql',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tgl', sa.String(length=20), nullable=True),
    sa.Column('rrn', sa.String(length=20), nullable=True),
    sa.Column('response_code', sa.String(length=10), nullable=True),
    sa.Column('proc_code', sa.String(length=10), nullable=True),
    sa.Column('acq_bank_nama', sa.String(length=50), nullable=True),
    sa.Column('iss_bank_nama', sa.String(length=50), nullable=True),
    sa.Column('merchant_name_location', sa.String(length=100), nullable=True),
    sa.Column('trx_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('film_actor', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_film_id')

    op.drop_table('film_actor')
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_index('film_fulltext_idx', postgresql_using='gist')
        batch_op.drop_index('idx_fk_language_id')
        batch_op.drop_index('idx_title')

    op.drop_table('film')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_city_id')

    op.drop_table('address')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('idx_store_id_film_id')

    op.drop_table('inventory')
    op.drop_table('category')
    op.drop_table('country')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_customer_id')
        batch_op.drop_index('idx_fk_rental_id')
        batch_op.drop_index('idx_fk_staff_id')

    op.drop_table('payment')
    op.drop_table('film_category')
    op.drop_table('language')
    op.drop_table('staff')
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_inventory_id')
        batch_op.drop_index('idx_unq_rental_rental_date_inventory_id_customer_id')

    op.drop_table('rental')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_address_id')
        batch_op.drop_index('idx_fk_store_id')
        batch_op.drop_index('idx_last_name')

    op.drop_table('customer')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_country_id')

    op.drop_table('city')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index('idx_unq_manager_staff_id')

    op.drop_table('store')
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_index('idx_actor_last_name')

    op.drop_table('actor')
    with op.batch_alter_table('data_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_acq', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_principal_acq', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nama_iss', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_principal_iss', sa.String(length=20), nullable=True))
        batch_op.alter_column('tgl',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('id_trx',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('transaction_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('transaction_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('response_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('rrn',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('proc_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('acq_bank_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('iss_bank_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('pan',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('acc_identification',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('merchant_name_location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('request',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('nama_id_principal')
        batch_op.drop_column('nama_id_principal_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_id_principal_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nama_id_principal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('request',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('merchant_name_location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('acc_identification',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('pan',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('iss_bank_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('acq_bank_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('proc_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('rrn',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('response_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('transaction_time',
               existing_type=sa.String(length=20),
               type_=postgresql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('transaction_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('id_trx',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('tgl',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('id_principal_iss')
        batch_op.drop_column('nama_iss')
        batch_op.drop_column('id_principal_acq')
        batch_op.drop_column('nama_acq')

    op.create_table('actor',
    sa.Column('actor_id', sa.INTEGER(), server_default=sa.text("nextval('actor_actor_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('actor_id', name='actor_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.create_index('idx_actor_last_name', ['last_name'], unique=False)

    op.create_table('store',
    sa.Column('store_id', sa.INTEGER(), server_default=sa.text("nextval('store_store_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('manager_staff_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('address_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='store_address_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_staff_id'], ['staff.staff_id'], name='store_manager_staff_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('store_id', name='store_pkey')
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index('idx_unq_manager_staff_id', ['manager_staff_id'], unique=False)

    op.create_table('city',
    sa.Column('city_id', sa.INTEGER(), server_default=sa.text("nextval('city_city_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name='fk_city'),
    sa.PrimaryKeyConstraint('city_id', name='city_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index('idx_fk_country_id', ['country_id'], unique=False)

    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), server_default=sa.text("nextval('customer_customer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('activebool', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('create_date', sa.DATE(), server_default=sa.text("('now'::text)::date"), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='customer_address_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('customer_id', name='customer_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('idx_last_name', ['last_name'], unique=False)
        batch_op.create_index('idx_fk_store_id', ['store_id'], unique=False)
        batch_op.create_index('idx_fk_address_id', ['address_id'], unique=False)

    op.create_table('rental',
    sa.Column('rental_id', sa.INTEGER(), server_default=sa.text("nextval('rental_rental_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('rental_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('staff_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='rental_customer_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], name='rental_inventory_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='rental_staff_id_key'),
    sa.PrimaryKeyConstraint('rental_id', name='rental_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.create_index('idx_unq_rental_rental_date_inventory_id_customer_id', ['rental_date', 'inventory_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_fk_inventory_id', ['inventory_id'], unique=False)

    op.create_table('staff',
    sa.Column('staff_id', sa.INTEGER(), server_default=sa.text("nextval('staff_staff_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('address_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('picture', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='staff_address_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('staff_id', name='staff_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('language',
    sa.Column('language_id', sa.INTEGER(), server_default=sa.text("nextval('language_language_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.CHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('language_id', name='language_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('film_category',
    sa.Column('film_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name='film_category_category_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='film_category_film_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('film_id', 'category_id', name='film_category_pkey')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.INTEGER(), server_default=sa.text("nextval('payment_payment_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='payment_customer_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.rental_id'], name='payment_rental_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='payment_staff_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id', name='payment_pkey')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_fk_staff_id', ['staff_id'], unique=False)
        batch_op.create_index('idx_fk_rental_id', ['rental_id'], unique=False)
        batch_op.create_index('idx_fk_customer_id', ['customer_id'], unique=False)

    op.create_table('country',
    sa.Column('country_id', sa.INTEGER(), server_default=sa.text("nextval('country_country_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('country_id', name='country_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('category',
    sa.Column('category_id', sa.INTEGER(), server_default=sa.text("nextval('category_category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category_id', name='category_pkey')
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.INTEGER(), server_default=sa.text("nextval('inventory_inventory_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='inventory_film_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_id', name='inventory_pkey')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index('idx_store_id_film_id', ['store_id', 'film_id'], unique=False)

    op.create_table('address',
    sa.Column('address_id', sa.INTEGER(), server_default=sa.text("nextval('address_address_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], name='fk_address_city'),
    sa.PrimaryKeyConstraint('address_id', name='address_pkey')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index('idx_fk_city_id', ['city_id'], unique=False)

    op.create_table('film',
    sa.Column('film_id', sa.INTEGER(), server_default=sa.text("nextval('film_film_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('rental_duration', sa.SMALLINT(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('rental_rate', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('4.99'), autoincrement=False, nullable=False),
    sa.Column('length', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('replacement_cost', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('19.99'), autoincrement=False, nullable=False),
    sa.Column('rating', postgresql.ENUM('G', 'PG', 'PG-13', 'R', 'NC-17', name='mpaa_rating'), server_default=sa.text("'G'::mpaa_rating"), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('special_features', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('fulltext', postgresql.TSVECTOR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], name='film_language_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('film_id', name='film_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.create_index('idx_title', ['title'], unique=False)
        batch_op.create_index('idx_fk_language_id', ['language_id'], unique=False)
        batch_op.create_index('film_fulltext_idx', ['fulltext'], unique=False, postgresql_using='gist')

    op.create_table('film_actor',
    sa.Column('actor_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('film_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], name='film_actor_actor_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='film_actor_film_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actor_id', 'film_id', name='film_actor_pkey')
    )
    with op.batch_alter_table('film_actor', schema=None) as batch_op:
        batch_op.create_index('idx_fk_film_id', ['film_id'], unique=False)

    op.drop_table('data_sql')
    # ### end Alembic commands ###
